### ISSUE TITLE
Break Out Unit Test into separate unit testing file.

### ISSUE THREAD

**Issue by juicedatom** [djhanove/autorally#3]
I'm not sure if this is a unit test or what.  But if it's a unit test then it should be broken out and properlly tested using a service like CppTest or Catch.

https://github.com/djhanove/autorally/blob/b09af86ebc8b6a8b934a53a1532bee135e0bb31d/autorally_control/src/LTVMPC/LTVMPC.cpp#L242

**Comment by djhanove** [comment]
It's just a terrible name for a function that was used while I was working on getting the concurrency implementation up and running. Will re-name for clarity
